### ISSUE TITLE
Replace old eslint config module

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#11]
Replace 
@blockone/eslint-config-blockone

**Comment by ericpassmore** [comment]
Create new file .eslintrc in base dir. 
[ESLint official website](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) for details.

**Comment by shaqk** [comment]
The dev dependency "@blockone/eslint-config-blockone" is now gone from npm

Not Found - GET https://registry.npmjs.org/@blockone/eslint-config-blockone/-/eslint-config-blockone-4.0.2.tgz - Not found

**Comment by ericpassmore** [comment]
Branch `ehp/GH-11-eslint-config` has the updates. Removed old packaged. Created new eslint and prettier config. Fixed one file `src/eosjs-jsonrpc.ts`. Package upgrades to eslint, typedoc, typescript, and node. Added eslint-config-prettier, eslint-plugin-es-x, eslint-plugin-prettier.  

ToDo: Need to test and `eslint --fix src/` all the other files as well. 
ToDo: Regenerate documentation and make sure they work 
ToDo: Rerun tests to make sure changes didn't break anything
