### ISSUE TITLE
Replace Deprecated TextEncoding

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#4]
**Version of EOSJS**
20.0.1

**Describe the bug**
One test file depends on unmaintained code text-encoding. Need to replace the code, or bring the code into this repository. This will eliminate a manual step and streamline the build

**To Reproduce**
The build requires a one-off step to run, running this will show the deprecated message
```npm install --save-dev text-encoding```

**Expected behavior**
build off tsconfig with not manual steps

**Screenshots**
None

**Desktop (please complete the following information):**
None

**Smartphone (please complete the following information):**
None

**Additional context**
[Text Encoding](https://www.npmjs.com/package/text-encoding)

**Comment by AlexGriffith10** [comment]
This has been completed
