### ISSUE TITLE
Check Deprecated Endpoints in 4.x

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#53]
### Work Title
Check for Deprecated Endpoints

#### `Requirements`
Return 299 http error codes for the following calls if they were previously supported in eosjs
`/v1/chain/abi_bin_to_json`
`/v1/chain/abi_json_to_bin`

#### `Design Notes`
299 is preferred. When the feature goes away use 404 error code. 

#### `Additional context`
[MDN Warnings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning)

**Comment by ericpassmore** [comment]
note need to check 4.x release notes https://github.com/AntelopeIO/leap/releases

**Comment by AlexGriffith10** [comment]
After checking repo neither of these endpoints seems to be in use. Closing the issue as not needed.
