### ISSUE TITLE
Remove bn library and use native BigInt

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#56]
Remove bignumber npm package and use native BigInt function. Check before and after size of package to measure improvement.

**Comment by juanm95** [comment]
the Elliptic package that we use also has BN as a dependency, so in order to fully get rid of it we might have to abandon Elliptic.

**Comment by ericpassmore** [comment]
That is a good point. I removed the good first issue tag. Considering closing this as won't fix.

**Comment by juanm95** [comment]
Is Elliptic an industry standard package or something? Maybe we try out another package that can do the same but without that BN dependency. If we can replace Elliptic I think it'd be worth doing, though maybe later.
