### ISSUE TITLE
Cleanup Unused npm Dependancies 

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#57]
### Work Title
Removed unused npm packages that are dependancies

### Notes
Depcheck looks like a good place to start
```
cd mandel-eosjs
npm install -g depcheck
depcheck
```

### Requirements
Safety first if you are unsure leave a package in place

**Comment by kellytran3k** [comment]
https://github.com/eosnetworkfoundation/mandel-eosjs/pull/61
