### ISSUE TITLE
Functional Tests Pass Without eosjs-ecc

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#59]
##  eosjs-ecc dependancies can be removed
Remove eosjs-ecc dependancy and file

## Steps to fix
rm eosjo-ecc.d.ts file under src
```
npm uninstall eosjs-ecc
```

## Testing 
```
npm run clean
npm run test # should pass
npm run test-node # should pass
```

**Comment by ericpassmore** [comment]
eosjs-ecc not used! Just figured that out after taking a look at the code

Current eosjs-ecc reads `declare module "eosjs-ecc";`.  No Exports. We can straight remove this dep.

**Comment by kellytran3k** [comment]
https://github.com/eosnetworkfoundation/mandel-eosjs/pull/61
