### ISSUE TITLE
Leap 4.0 Endpoint Rationalization

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/mandel-eosjs#63]
### Work Title
Rationalize endpoints in eosjs targeting Leap 4.0

#### `Requirements`
Review the list below, and test them. File an issue to remove unsupported endpoints. 
Compare the list below to the chain plugin in leap and file an issue to add missing endpoints. 

To see 4.0 chain endpoint copy and paste this swagger https://github.com/AntelopeIO/leap/blob/release/4.0/plugins/chain_api_plugin/chain.swagger.yaml
into this tool https://editor.swagger.io/

#### `Scenarios`

- /v1/chain/get_abi
- /v1/chain/get_account
- /v1/chain/get_block_header_state
- /v1/chain/get_block
- /v1/chain/get_code
- /v1/chain/get_currency_balance
- /v1/chain/get_currency_stats
- /v1/chain/get_info
- /v1/chain/get_producer_schedule
- /v1/chain/get_producers
- /v1/chain/get_raw_code_and_abi
- /v1/chain/get_scheduled_transactions
- /v1/chain/get_table_rows
- /v1/chain/get_table_by_scope
- /v1/chain/get_required_keys
- /v1/chain/push_transaction
- /v1/chain/send_transaction
- /v1/chain/send_transaction2

### Additional Tests
if you have a 4.0 instance of leap running you may run curl requests to test out these endpoints

`curl -v http://localhost:8888/v1/chain/get_info`

**Comment by AlexGriffith10** [comment]
Double checked all the above endpoints are in use

Also doesn't look like there are any extra endpoints floating around that aren't on the list.
